name: Snowflake_Dev_Deployments

on:
  push:
    #branches:
      #- dev
    #paths:
      #- 'dbscripts/usrs/**'
  
  workflow_dispatch:
jobs:	
  Dev_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#Calling Accounts ChangeLog
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.DEVDB_ACC_URL }} --username=${{ secrets.DEVDB_ACC_USERNAME }} --password=${{ secrets.DEVDB_ACC_PASSWORD }} --default-schema-name=${{ secrets.DEVDB_ACC_SCHEMA }} --databaseChangeLogTableName=DATABASECHANGELOG1 --databaseChangeLogLockTableName=DATABASECHANGELOGLOCK1 --changeLogFile=/dbscripts/deploy/AccountsChangeLog.xml status
    - name:  Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.DEVDB_ACC_URL }} --username=${{ secrets.DEVDB_ACC_USERNAME }} --password=${{ secrets.DEVDB_ACC_PASSWORD }} --default-schema-name=${{ secrets.DEVDB_ACC_SCHEMA }} --databaseChangeLogTableName=DATABASECHANGELOG1 --databaseChangeLogLockTableName=DATABASECHANGELOGLOCK1 --changeLogFile=/dbscripts/deploy/AccountsChangeLog.xml --contexts="dev" update -DEnvVar=""

#Calling Database ChangeLog
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.DEVDB_URL }} --username=${{ secrets.DEVDB_USERNAME }} --password=${{ secrets.DEVDB_PASSWORD }} --default-schema-name=${{ secrets.DEVDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml status
    - name:  Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.DEVDB_URL }} --username=${{ secrets.DEVDB_USERNAME }} --password=${{ secrets.DEVDB_PASSWORD }} --default-schema-name=${{ secrets.DEVDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml --contexts="dev" update -DEnvVar=""

