name: Snowflake_Test_Deployments

on:
  push:
    branches:
      - test
    paths:
      - 'dbscripts/**'
  workflow_dispatch:
jobs:	
  Test_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.TESTDB_URL }} --username=${{ secrets.TESTDB_USERNAME }} --password=${{ secrets.TESTDB_PASSWORD }} --default-schema-name=${{ secrets.TESTDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml status
    - name:  Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.TESTDB_URL }} --username=${{ secrets.TESTDB_USERNAME }} --password=${{ secrets.TESTDB_PASSWORD }} --default-schema-name=${{ secrets.TESTDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml update
