name: Snowflake_Prod_Deployments
on: push

jobs:
  Shell_Script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: sh ./.github/workflows/export.sh
      shell: bash
          #with:
            #password: ${{ secrets.Curll_Pwd }}
    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.CURL_PW }}
      run: |
        import os
        data = open("file", "w")
        for q in (os.getenv("MY_VAL")):
          print q
          data.write(q)
      shell: python
