name: Snowflake_Prod_Deployments

on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'
  workflow_dispatch:
jobs:	
  Prod_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.PRODDB_URL }} --username=${{ secrets.PRODDB_USERNAME }} --password=${{ secrets.PRODDB_PASSWORD }} --default-schema-name=${{ secrets.PRODDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml status
    - name:  Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.PRODDB_URL }} --username=${{ secrets.PRODDB_USERNAME }} --password=${{ secrets.PRODDB_PASSWORD }} --default-schema-name=${{ secrets.PRODDB_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml update
