name:  Env Vars

on:
  push:
    paths:
     - '**'
     - '!.github/**'
     - '.github/workflows/sample.yml'
     - '!**.md'           # do not run on doc change
     
  workflow_dispatch:
env:
  WF_ENV: Available to all jobs
jobs:  
  Log-Env:
    runs-on: ubuntu-latest
    env:
      JOBS_ENV: Available to all steps in this job
    steps:
      - name: Job Env vars
        env:
          STEPS_ENV: Available to this step only
          run: |
            echo "WF_ENV: ${WF_ENV}"
            echo "JOBS_ENV: ${JOBS_ENV}"
            echo "STEPS_ENV: ${STEPS_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default Env Vars
        run: |
          echo "HOME:${HOME}"
          echo "GITHUB_WORKFLOW:${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION:${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS:${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR:${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME:${GITHUB_EVENT_NAME}"
          echo "GITHUB_SHA:${GITHUB_SHA}"
          echo "GITHUB_REF:${GITHUB_REF}"
          echo "WF_ENV:${WF_ENV}"
          echo "JOBS_ENV:${JOBS_ENV}"
          echo "STEPS_ENV:${STEPS_ENV}"
          
