name:  Shell types

on:
  push:
    paths:
     - '**'
     - '!.github/**'
     - '.github/workflows/sample.yml'
     - '!**.md'           # do not run on doc change
     
  workflow_dispatch:

jobs:  
  runs-shell-types:
    runs-on:  ubuntu-latest
    steps:
      - name: echo a string
        run:  echo "This is a string"
      - name: Python Commands
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  runs-windows-commands:
    runs-on:  windows-latest
    needs: ["runs-shell-types"]
    steps:
      - name: Folder PowerShell 
        run: Get-Location
      - name: Directory
        run: pwd
        shell:  bash
