name:  Shell Commands

on:  [push]

jobs:  
  runs-shell-commands:
    runs-on:  ubuntu-latest
    steps:
      - name: echo a string
        run:  echo "This is a string"
      - name: multi commands
        run: |
          git -v
          node -v
