name:  Env Vars

on:
  push:
    paths:
     - '**'
     - '!.github/**'
     - '.github/workflows/sample.yml'
     - '!**.md'           # do not run on doc change
     
  workflow_dispatch:
env:
  WF_ENV: Available to all jobs
jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt File
        run:  gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output ./my_secret.json ./sample.json.gpg
        env:
          PASSPHRASE: ${{ secrets.mypin }}
      - name: Cat the File
        run: cat ./my_secret.json
  Log-Env:
    runs-on: ubuntu-latest
    env:
      JOBS_ENV: Available to all steps in this job
    steps:
      - name: Job Env vars
        env:
          STEPS_ENV: Available to this step only
        run: |
            echo "WF_ENV: ${WF_ENV}"
            echo "JOBS_ENV: ${JOBS_ENV}"
            echo "STEPS_ENV: ${STEPS_ENV}"
