name:  Env Vars

on:
  push:
    paths:
     - '**'
     - '!.github/**'
     - '.github/workflows/sample.yml'
     - '!**.md'           # do not run on doc change
     
  workflow_dispatch:
env:
  WF_ENV: Available to all jobs
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run:  |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startswith( 'hello', 'he' ) }}
          echo ${{ endswith( 'hello', 'lo' ) }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!' ) }}

  One:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
